### ISSUE TITLE
<a href> not working anymore using referers in my code 

### ISSUE THREAD

**Issue by IronTony** [Thomas101/react-native-fence-html#14]
Hello,
using `renderers={renderers}` the `onLinkPress={(evt, href) => Linking.openURL(href)}` doesn't work anymore.
Anyone else got this problem?

**Comment by IronTony** [comment]
Totally my fault. I wrote renderers inside the HTML component tag in the render!

**Comment by IronTony** [comment]
If I write the renderers outside the <HTML .... /> the links work, but not the custom tags like table, tbody, tr, td, and so on.
Viceversa everything works except the A HREF

**Comment by vince-rowe** [comment]
I'm also seeing this, I needed to write the renderer (as used in the readme) so I could work with the images dimensions. Doing so needs to call renderers={renderers} in the tag, but in doing that it disables all links (a tags).

Is there any help on this, even if its just the renderer code to place in the page similar to what was used in the readme for the image example?

**Comment by vince-rowe** [comment]
Looks like this has been resolved here: #12
