### ISSUE TITLE
Warning: Failed propType: Invalid props.htmlStyles key `h3` supplied to

### ISSUE THREAD

**Issue by xcplus** [Thomas101/react-native-fence-html#2]
Warning: Failed propType: Invalid props.htmlStyles key `h3` supplied to
`HTMLElement`.
Bad object: {
  "h3": {
    "borderWidth": 2
  }
}
Valid keys: [
  "width",
  "height",
  "top",
  "left",
  "right",
  "bottom",
  "margin",
  "marginVertical",
  "marginHorizontal",
  "marginTop",
  "marginBottom",
  "marginLeft",
  "marginRight",
  "padding",
  "paddingVertical",
  "paddingHorizontal",
  "paddingTop",
  "paddingBottom",
  "paddingLeft",
  "paddingRight",
  "borderWidth",
  "borderTopWidth", ....]

**Comment by Thomas101** [comment]
Whoops, just a prop validation typo. This is fixed now
