### ISSUE TITLE
Question:: What WYSIWYG do you recommend?

### ISSUE THREAD

**Issue by donedgardo** [Thomas101/react-native-fence-html#6]
I was using [Freola](https://www.froala.com/wysiwyg-editor), but most of its styles are mostly with css files not inline.
Can you recommend anything else?
Its for a blog App.
 Thank you in advance.

**Comment by Thomas101** [comment]
On the ReactNative side I don't know of any other libraries that support this. On the wysiwyg side I have used [Redactor](https://imperavi.com/redactor/) on some other projects. I think this uses inline styles. It is paid for though, so you probably want to see if does work before paying for it.

If there's a pretty fixed set of styles I imagine you could pass them through and apply them with relative ease. At a quick glance I think you could do it by adding the following....

1.) In `HTML. renderHtmlAsRN` pass `node.class` to `<HTMLElement ... />` (it might be node.className)
2.) In `HTMLElement.render` there's an array of styles built up. You could add another set into here, for example....

``` js
const style = []
        .concat(
          HTMLStyles.defaultStyles[tagName],
          htmlStyles ? htmlStyles[tagName] : undefined,
++          htmlStyles ? htmlStyles[this.props.className] : undefined,
          htmlAttribs.style ? HTMLStyles.cssStringToRNStyle(htmlAttribs.style, styleset) : undefined
        ).filter((s) => s !== undefined)
```

3.) Convert the css styles to RN styles and pass them into `HTML` under the `htmlStyles` prop

I would have a go at adding it in, but I don't have a lot of spare time over the next couple of weeks. If you do get it working though would be great to have a pull request :-)
