### ISSUE TITLE
Yellow Box Error

### ISSUE THREAD

**Issue by aestrro** [Thomas101/react-native-fence-html#7]
## Version

"react-native-fence-html": "^1.0.5",
"react-native": "0.27.2",
### Expected Result

No Yellowbox Error
### Actual Result

Yellowbox error displays expressing that I have  the following:
`
Failed propType: invalid props.htmlStyles key 'p' supplied to 'HTMLElement'.
Bad object: {
  "p": {
      ....
  }
}
`

**Comment by felipemartim** [comment]
Try this fork to see if it works:
https://github.com/gbaladi/react-native-fence-html

I believe a PR should be sent to fix the issue.

**Comment by Thomas101** [comment]
I've patched this in 1.0.6. Thanks!
