### ISSUE TITLE
EPEERINVALID react-addons-shallow-compare

### ISSUE THREAD

**Issue by felipemartim** [Thomas101/react-native-fence-html#8]
Since React Native started using 15.x.x versions of react, I keep getting the following warning from npm:

`npm WARN EPEERINVALID react-addons-shallow-compare@0.14.8 requires a peer of react@^0.14.8 but none was installed.`

@gbaladi already updated this dependency on his/her fork, as can be seen here:
https://github.com/gbaladi/react-native-fence-html/commit/868ac3a98cfaad75fbfa8ddde9212346ce2b4f71

Maybe a PR should be sent to fix this or @Thomas101 can just update the dependency.

**Comment by Thomas101** [comment]
Thanks! I've made react-native-shallow-compare a peer dependency of >=0.14.8
